### PR TITLE
Brazilian Portuguese Version for Proactive Controls

### PR DESCRIPTION
**Pull request by soareswallace**

### CODE REVIEW

**Comment by soareswallace** [comment]
@jmanico Thanks for your quick merge. When you add the contribution to the page you can add either my email (soareswallace@icloud.com) or my linkedin(https://www.linkedin.com/in/soareswallace1/)

I appreciate your work and look forward for new contributions! :)

**Comment by jmanico** [comment]
Can you kindly issues a PR with your contributor info here?

https://github.com/OWASP/www-project-proactive-controls/blob/master/index.md

Aloha, Jim

**Comment by soareswallace** [comment]
Of course! In a minute

**Comment by soareswallace** [comment]
Done https://github.com/OWASP/www-project-proactive-controls/pull/15

**Pull request merged**
