### PR TITLE
enforcement -> descision

### PR DESCRIPTION
**Pull request by wurstbrot**
From my point of view, it is a policy decisions point. The enforcement would be the location, e.g. in the java filter.

### CODE REVIEW

**Comment by katyanton** [comment]
commit has a type: Descision instead of Decision

**Comment by andreashappe** [comment]
Hi, I believe that "policy enforcement" is the accepted industry term, please see also https://en.wikipedia.org/wiki/Attribute-based_access_control (PEP -> "Policy Enforcement Point").

I am not sure if you are not happy with the term itself or if the term is wrongly used, could you please clarify?

Thanks, Andreas

**Comment by jmanico** [comment]
The policy enforcement point (PEP) is the place in the code that does the access control check. I advise to keep away from hard coding roles when it comes to policy enforcement points.

Policy decision points are how all the criteria is used to make an access control decision, the implementation that is called by the PEP.

Fair?

**Comment by andreashappe** [comment]
hm, let's add this as a short introduction to the document?

**Pull request closed without merging**
